apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:                 # Corretto da metadata: a template:
    metadata:
      labels:
        app: mongo
    spec:                     # Aggiunto spec: all'interno di template:
      containers:
        - name: mongo
          image: ciccio2305/justsmartmongo:latest
          args: ["--replSet", "rs0"]  # Aggiungi questa riga per abilitare il replicaset
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  mongosh --quiet --eval "try { rs.initiate() } catch(e) { rs.status().ok }" | grep 1
            initialDelaySeconds: 5
            periodSeconds: 30
          ports:                # Indentazione corretta, al livello di `containers`
            - containerPort: 27017
          volumeMounts:          # Indentazione corretta, al livello di `containers`
            - name: mongo-storage
              mountPath: /data/db
      volumes:                  # Indentazione corretta, al livello di `spec` (non sotto `containers`)
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
